/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bcirs;

import bcirs.login_form;
import config.PasswordHasher;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author SCC-COLLEGE
 */
public class forgotpass_code extends javax.swing.JFrame {

    /**
     * Creates new form resgiter_form
     */
    public forgotpass_code() {
        initComponents();
          sc.setBorder(new EmptyBorder(0,10,0,0));
    }
    
    Color Red = new Color(255,0,0);
    Color Hover = new Color(0,102,255);
    Color Release = new Color(27,57,77);


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        cBt = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        hide1 = new javax.swing.JLabel();
        show1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        signIn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sc = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 55, 77));
        jLabel1.setText("Two-factor Authentication");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 440, 47));

        email.setBackground(new java.awt.Color(234, 234, 234));
        email.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(27, 55, 77));
        email.setText("email");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 200, 30));

        cBt.setBackground(new java.awt.Color(27, 55, 77));
        cBt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cBt.setForeground(new java.awt.Color(255, 255, 255));
        cBt.setText("Verify");
        cBt.setBorder(null);
        cBt.setBorderPainted(false);
        cBt.setOpaque(false);
        cBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cBtMouseExited(evt);
            }
        });
        cBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBtActionPerformed(evt);
            }
        });
        jPanel2.add(cBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 190, 35));

        jLabel11.setBackground(new java.awt.Color(234, 234, 234));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(27, 55, 77));
        jLabel11.setText("We have verified your email address. To continue, kindly enter");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 420, 30));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(27, 55, 77));
        jLabel16.setText("Security code");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 90, 40));

        a1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 0, 0));
        a1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 260, 30));

        hide1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        hide1.setForeground(new java.awt.Color(153, 153, 153));
        hide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eye-crossed.png"))); // NOI18N
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide1MousePressed(evt);
            }
        });
        jPanel2.add(hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 303, -1, -1));

        show1.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        show1.setForeground(new java.awt.Color(153, 153, 153));
        show1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eye.png"))); // NOI18N
        show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show1MouseClicked(evt);
            }
        });
        jPanel2.add(show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 303, -1, -1));

        jPanel5.setBackground(new java.awt.Color(27, 55, 77));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Security On-amico (1)_1.png"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 262));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 581, 560));

        jLabel12.setBackground(new java.awt.Color(234, 234, 234));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 55, 77));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("the secuirty code authorized by");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 210, 30));

        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("jLabel3");
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 140, -1));

        signIn.setBackground(new java.awt.Color(245, 246, 248));
        signIn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        signIn.setForeground(new java.awt.Color(27, 55, 77));
        signIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signIn.setText("Login again");
        signIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInMouseExited(evt);
            }
        });
        jPanel2.add(signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 130, 60));

        jLabel10.setBackground(new java.awt.Color(234, 234, 234));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Remember Password?");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 140, 50));

        sc.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 420, 40));
        sc.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBtActionPerformed
     
     a1.setText("");   
        
     dbConnector dbc = new dbConnector();
     String u_id = id.getText();
     
     PasswordHasher pH = new PasswordHasher();       
        
        try {
          String query = "SELECT * FROM tbl_user WHERE u_id = '" + u_id + "'";
          ResultSet rs = dbc.getData(query);
            
           if (rs.next()) {
            
             String code = pH.hashPassword(sc.getText());
             String securityCode = rs.getString("u_code");
                
             if(sc.getText().isEmpty()){
                 
                if(sc.getText().isEmpty()){
                  a1.setText("Field required");
                }
             }else if(!code.equals(securityCode)){
                  a1.setText("Invalid code");              
             }else{
                 System.out.println("code valid");
                 
                 resetPass rp = new resetPass();
                 rp.id.setText(u_id);
                 rp.setVisible(true);
                 this.dispose();
                
             }
             
          }
                   
  
        } catch (SQLException ex) {
            System.out.println(ex);
        }

                         
    }//GEN-LAST:event_cBtActionPerformed

    private void cBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cBtMouseEntered
         cBt.setBackground(Hover);
    }//GEN-LAST:event_cBtMouseEntered

    private void cBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cBtMouseExited
         cBt.setBackground(Release);
    }//GEN-LAST:event_cBtMouseExited

    private void signInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMouseClicked
        login_form log = new login_form();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signInMouseClicked

    private void signInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMouseEntered
        signIn.setForeground(Hover);
    }//GEN-LAST:event_signInMouseEntered

    private void signInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMouseExited
        signIn.setForeground(Release);
    }//GEN-LAST:event_signInMouseExited

    private void hide1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MousePressed
        hide1.setVisible(false);
        show1.setVisible(true);
        sc.setEchoChar((char) 0);
    }//GEN-LAST:event_hide1MousePressed

    private void show1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show1MouseClicked
        hide1.setVisible(true);
        show1.setVisible(false);
        sc.setEchoChar('\u25CF');
    }//GEN-LAST:event_show1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpass_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpass_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpass_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpass_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpass_code().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JButton cBt;
    public javax.swing.JLabel email;
    private javax.swing.JLabel hide1;
    public javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField sc;
    private javax.swing.JLabel show1;
    private javax.swing.JLabel signIn;
    // End of variables declaration//GEN-END:variables
}
